### ISSUE TITLE
http status: 500 Internal Server Error

### ISSUE THREAD

**Issue by a-velt** [ebi-wp/webservice-clients#6]
Hi,

I tried the ncbiblast.pl script with the following command on Centos6 : 

/cmm/shared/apps/webservice-clients/perl/ncbiblast.pl sample_prot.fasta --program blastp --database uniprotkb_swissprot --alignments 20 --scores 20 --maxJobs 30 --stype protein --email mail@gmail.com --multifasta --useSeqId

And I got following error : 

Submitting job for: 000000F_003g0281251_1
JobId: ncbiblast-R20190701-140920-0894-43925861-p1m
FINISHED
Creating result file: 000000F_003g0281251_1.out.txt
Creating result file: 000000F_003g0281251_1.sequence.txt
Creating result file: 000000F_003g0281251_1.ids.txt
Creating result file: 000000F_003g0281251_1.accs.txt
Creating result file: 000000F_003g0281251_1.xml.xml
Creating result file: 000000F_003g0281251_1.visual-svg.svg
Creating result file: 000000F_003g0281251_1.complete-visual-svg.svg
Creating result file: 000000F_003g0281251_1.visual-png.png
Creating result file: 000000F_003g0281251_1.complete-visual-png.png
http status: 500 Internal Server Error   at /cmm/shared/apps/webservice-clients/perl/ncbiblast.pl line 293.

This is a problem of NCBI certificate ? How can I create a certificate for NCBI ? 

Thank you for your help.
Best,
Amandine

**Comment by biomadeira** [comment]
Dear @a-velt,

Thanks for reporting. https://github.com/ebi-wp/webservice-clients/commit/c65f1683ba7dca490ff5bb5358c55b34365dc719 should fix this issue.

Fábio

**Comment by a-velt** [comment]
Thank you for your response, but it doesn't work for me.

I took your modifications : 
```
commit c65f1683ba7dca490ff5bb5358c55b34365dc719
Author: Fábio Madeira <fbiomadeira@gmail.com>
Date:   Wed Jul 3 12:55:59 2019 +0100

    JD-328 Fixed problem with some urlopen calls with requests (new dependency)
```

Launched my command : 

`/shared/apps/webservice-clients/perl/ncbiblast.pl sample_prot.fasta --program blastp --database uniprotkb_swissprot --alignments 20 --scores 20 --maxJobs 30 --stype protein --email mail@gmail.com --multifasta --useSeqId`

And have the same error : 

> Submitting job for: A
> JobId: ncbiblast-R20190703-153400-0087-10286944-p1m
> FINISHED
> Creating result file: A.out.txt
> Creating result file: A.sequence.txt
> Creating result file: A.ids.txt
> Creating result file: A.accs.txt
> Creating result file: A.xml.xml
> Creating result file: A.visual-svg.svg
> Creating result file: A.complete-visual-svg.svg
> Creating result file: A.visual-png.png
> Creating result file: A.complete-visual-png.png
> http status: 500 Internal Server Error   at /shared/apps/webservice-clients/perl/ncbiblast.pl line 293.

Best,
Amandine

**Comment by biomadeira** [comment]
Ups, sorry! I didn't realize you were using the Perl client. I have fixed the Python ones but will do the same for the Perl ones. Let me give it a go.

**Comment by biomadeira** [comment]
@a-velt this one https://github.com/ebi-wp/webservice-clients/commit/cc19d0ac5682f763ad1c6d530fe9a5a523a82a2b should do it :)

**Comment by biomadeira** [comment]
BTW, in case you only need some particular type of output you could add the param `--outformat` with one or more output types (e.g. `--outformat out,ids`)
